ALTER TABLE PERSON DROP CONSTRAINT PERSON_ORGUNIT_ID
ALTER TABLE ORGUNIT DROP CONSTRAINT ORGUNIT_managedby
ALTER TABLE ORGUNIT DROP CONSTRAINT ORGUNIT_subunitof
ALTER TABLE MISSION DROP CONSTRAINT MISSIONrequestedBy
ALTER TABLE MISSION_PERSON DROP CONSTRAINT MSSNPRSNprfrmdByID
ALTER TABLE MISSION_PERSON DROP CONSTRAINT MSSNPERSONmssonsID
DROP TABLE PERSON
DROP TABLE ORGUNIT
DROP TABLE MISSION
DROP TABLE MISSION_PERSON
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
DROP TABLE SEQUENCE